### ISSUE TITLE
Issue: 스프링 시큐리티 관련 이슈

### ISSUE THREAD

**Issue by dnjfqhd12345** [Step3-kakao-tech-campus/Team12_BE#14]
## Description
`.requestMatchers(new AntPathRequestMatcher("/users/register/input")).hasAuthority("ROLE_GUEST")`
이런식으로 권한 처리를 했음에도 불구하고 해당 URL에 대한 권한 처리가 되질 않음.

이외 코드 컨벤션, 토큰/쿠키 만료시간도 생각해봐야 할 문제 (상의 없이 임의로 만료기간을 넣었다.)

## Todo
- [x] 권한처리 안되는 이유 찾아보기
- [x] 코드 컨벤션 확인하기
- [x] 토큰/쿠키 만료시간 이야기하기

## ETC
기타사항
