### ISSUE TITLE
issue : beverage를 List로 하지않은 문제

### ISSUE THREAD

**Issue by LJH098** [Step3-kakao-tech-campus/Team12_BE#25]
## Description
하나의 공고글에 여러개의 음료를 선택할 수 있는데 List형식으로 하지않아서 1개밖에 못받아오는 현상

##선택
Board 조회할때 beverage 에 대한 정보 (음료 이름)을 가져와야 하기 때문에 Board와 Beverage에 @OneToMany를 추가 하거나 beverage_tb에서 해당 boardId로 beverage 가져오는 방법 중 하나를 선택해야함
- [x] Board 와 Beverage @OneToMany
- [ ] board_tb에서 boardId로 beverage 가져오기
## Todo
- [x] 선택에서 고른것 하기
- [x] DTO에서 beverage 관련 필드는 List로 바꾸기
- [x] Board 생성 로직 수정
## ETC
기타사항
