### ISSUE TITLE
issue: JwtAuthenticationProcessingFilter 로직 수정

### ISSUE THREAD

**Issue by dnjfqhd12345** [Step3-kakao-tech-campus/Team12_BE#49]
## Description
JwtAuthenticationProcessingFilter 필터 관련해서 AccessToken과 RefreshToken 검증 과정에서 잘못된 로직이 있어 수정함.

## Todo
- [x] 의미없는 주석처리랑 잘못된 주석 삭제
- [x] JwtService 트랜잭션 관리 추가
- [x] checkRefreshTokenAndReIssueAccessToken에서 AccessToken도 발급처리
- [x] doFilterInternal() 메서드에서 JWT 검증 관련한 로직 중 잘못된 부분 수정

## ETC
기타사항
